version: 1
build:
  main: cmd/blitd/
accounts:
- name: alice
  coins:
  - 200000000blit
- name: bob
  coins:
  - 100000000blit
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000blit
validators:
- name: alice
  bonded: 100000000blit
genesis:
  chain_id: "blit-dev"
  consensus_params:
    block:
      max_gas: "3000000"
      max_bytes: "2000000"
  app_state:
    staking:
      params:
        bond_denom: "blit"
    mint:
      params:
        mint_denom: "blit"
    crisis:
      constant_fee:
        denom: "blit"
    gov:
      voting_params:
        voting_period: "30s"
      deposit_params:
        min_deposit:
            - amount: "1000"
              denom: "blit"

