version: "3.9"

services: 
  blit:
    init: true
    build: 
      context: .
    image: blitchain/blitchain:${BLIT_VERSION-dev}
    ports: 
      - "26656-26657:26656-26657"
      - "1317:1317"
    volumes:
      - ${DEAMON_HOME-~/.blit}:/home/user/.blit
