version: 1
build:
  main: cmd/blitd/
  proto:
    path: "./proto/"
    third_party_paths: []
accounts:
- name: alice
  coins:
  - 10000000000000ublit
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
      - name: Blit
        description: The native staking token of Blitchain
        denom_units:
        - denom: ublit
          exponent: 0
          aliases: ["microblit"]
        - denom: blit
          exponent: 6
        base: ublit
        display: blit
        symbol: BLT
    crisis:
      constant_fee:
        denom: blit
    gov:
      params:
        min_deposit:
        - amount: "1000"
          denom: blit
        voting_period: 30s
    mint:
      params:
        goal_bonded: "0.67"
        inflation_max: "0.10"
        inflation_min: "0.01"
        inflation_rate_change: "0.10"
        mint_denom: ublit
    staking:
      params:
        bond_denom: ublit
  chain_id: blit-dev
  consensus_params:
    block:
      max_bytes: "2000000"
      max_gas: "3000000"
validators:
- name: alice
  bonded: 100000000ublit
  client:
    output: "json"
  app:
    state-sync:
      snapshot-interval: "10"
      snapshot-keep-recent: "2"


