version: 1
build:
  main: cmd/blitd/
  proto:
    path: ""
    third_party_paths: []
accounts:
- name: alice
  mnemonic: about round cry leisure vague idea park drop minor double horse occur despair cool lazy floor betray network midnight bonus oak couch crime write
  coins:
  - 200000000blit
- name: bob
  coins:
  - 100000000blit
faucet:
  name: bob
  coins:
  - 100000blit
client:
  typescript:
    path: ../blit-client-ts
  composables:
    path: ../vue-composables
  hooks:
    path: ../react-hooks
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: blit
    gov:
      deposit_params:
        min_deposit:
        - amount: "1000"
          denom: blit
      voting_params:
        voting_period: 30s
    mint:
      params:
        mint_denom: blit
    staking:
      params:
        bond_denom: blit
  chain_id: blit-dev
  consensus_params:
    block:
      max_bytes: "2000000"
      max_gas: "3000000"
validators:
- name: alice
  bonded: 100000000blit
